<a id='toc_nb'></a>   

#### Table of Contents

 - [Example](#example) 
 - [Partition ](#partition) 
 - [Distribution ](#distribution) 
 - [Model ](#model) 

In [1]:
DPATH = "/home/Strontium/Code_Files/Datasets/"

In [ ]:
print(DPATH)

In [2]:
import os, re, sys
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
np.set_printoptions(linewidth=128)

cols = np.arange(785)

#DPATH = str(os.path.abspath(os.path.pardir)) + '/Datasets/data/'#Strontium
DPATH = str(os.path.abspath(os.path.pardir)) + '/Datasets/'
df = pd.read_csv(DPATH+"mnist_train.csv", names=cols)
df.describe()

0        1        2        3        4        5        6    \
count  60000.000000  60000.0  60000.0  60000.0  60000.0  60000.0  60000.0   
mean       4.453933      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.889270      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

           7        8        9        10       11       12            13   \
count  60000.0  60000.0  60000.0  60000.0  60000.0  60000.0  60000.000000   
mean       0.0      0.0      0.0      0.0      0.0      0.0      0.002100   
std        0.0      0.0      0.0      0.0      0.0      0.0      0.475324   
min        0.0      0.0      0.0      0.0      0.0      0.0      0.000000   
25%        0.0      0.0      0.0      0.0      0.0      0.0      0.000000   
50%        0.0      0.0      0.0      0.0      0.0      0.0      0.000000   
75%        0.0      0.0      0.0      0.0      0.0      0.0      0.000000   
max        0.0      0.0      0.0      0.0      0.0      0.0    116.000000   

                14            15            16       17       18       19   \
count  60000.000000  60000.000000  60000.000000  60000.0  60000.0  60000.0   
mean       0.007833      0.003600      0.000150      0.0      0.0      0.0   
std        1.361189      0.881816      0.036742      0.0      0.0      0.0   
min        0.000000      0.000000      0.000000      0.0      0.0      0.0   
25%        0.000000      0.000000      0.000000      0.0      0.0      0.0   
50%        0.000000      0.000000      0.000000      0.0      0.0      0.0   
75%        0.000000      0.000000      0.000000      0.0      0.0      0.0   
max      254.000000    216.000000      9.000000      0.0      0.0      0.0   

           20       21       22       23       24       25       26       27   \
count  60000.0  60000.0  60000.0  60000.0  60000.0  60000.0  60000.0  60000.0   
mean       0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
std        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
25%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
50%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
75%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
max        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

           28       29       30       31       32            33   \
count  60000.0  60000.0  60000.0  60000.0  60000.0  60000.000000   
mean       0.0      0.0      0.0      0.0      0.0      0.000267   
std        0.0      0.0      0.0      0.0      0.0      0.065320   
min        0.0      0.0      0.0      0.0      0.0      0.000000   
25%        0.0      0.0      0.0      0.0      0.0      0.000000   
50%        0.0      0.0      0.0      0.0      0.0      0.000000   
75%        0.0      0.0      0.0      0.0      0.0      0.000000   
max        0.0      0.0      0.0      0.0      0.0     16.000000   

                34            35            36            37           38   \
count  60000.000000  60000.000000  60000.000000  60000.000000  60000.00000   
mean       0.000917      0.009283      0.024283      0.043717      0.06410   
std        0.194636      1.055011      2.095113      2.962063      3.32388   
min        0.000000      0.000000      0.000000      0.000000      0.00000   
25%        0.000000      0.000000      0.000000      0.000000      0.00000   
50%        0.000000      0.000000      0.000000      0.000000      0.00000   
75%        0.000000      0.000000   

In [3]:
np.set_printoptions(linewidth=164)

<a id='example'></a>   

###### [Back to TOC](#toc_nb)  [Next ](#partition)  
### Example  
This is an example to illustrate the nature of the data

In [4]:
s = df.loc[np.random.randint(0,60000)]
s = np.asarray(s)[1:785].reshape((28,28))
#s = np.asarray(df.sample(1)[1:785]).reshape(28,28)
print(s)

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 217 246 156  66  36   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 126 253 253 253 238 132  19   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 194 179 108 186 253 254 247 175  74   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  68 192  18   0   3  19 139 232 253 250 159   0   

In [17]:
#df = pd.read_csv("ann_Test_v1.csv")
#df.describe()

<a id='partition'></a>   

###### [Back to TOC](#toc_nb) [Previous ](#example) [Next ](#distribution) 
### Partition  
Separating each class into it's own group for further processing

In [5]:
df0 = df[df.iloc[:,0]==0].sample(n=5400,replace=False)
df1 = df[df.iloc[:,0]==1].sample(n=5400,replace=False)
df2 = df[df.iloc[:,0]==2].sample(n=5400,replace=False)
df3 = df[df.iloc[:,0]==3].sample(n=5400,replace=False)
df4 = df[df.iloc[:,0]==4].sample(n=5400,replace=False)
df5 = df[df.iloc[:,0]==5].sample(n=5400,replace=False)
df6 = df[df.iloc[:,0]==6].sample(n=5400,replace=False)
df7 = df[df.iloc[:,0]==7].sample(n=5400,replace=False)
df8 = df[df.iloc[:,0]==8].sample(n=5400,replace=False)
df9 = df[df.iloc[:,0]==9].sample(n=5400,replace=False)

In [6]:
dflist = [df0,df1,df2,df3,df4,df5,df6,df7,df8,df9]

In [7]:
avg0 = np.zeros((10,784), dtype=int)
for k in range(10):
    dfk=dflist[k] # for each class...
    for i in range(784): # ...for each feature...
        avg0[k][i] = int(sum(dfk[i])/(5400))# ...create a 'distribution'

In [14]:
a00 = np.asarray(df0[10])

<a id='distribution'></a>   

###### [Back to TOC](#toc_nb) [Previous ](#partition) [Next ](#model)  
### Distribution  
What does p(x|y) mean in terms of this form? The distribution is the values in the channel (i.e.  
5400 for each of the 784 'channels')? That doesn't seem right. If it were, what follows would  
be the mean of the distribution for each 'channel'. What is the right way to describe p(x|y)?  
Maybe try binning the values along each channel to view them?
p(x1,x2,...x784|y)  
Gaussians of Gaussians. 784 Gaussians for each class, 1 for each set of Gaussians  
multidimensional Gaussian vs mixture
look up 'fittng Gaussian to multidimensional data'
do deep dive into what gaussian mixture model and EM _ARE_   
Read the Murphy text on GMM and EM 1st, then the paper `A_Fast_Method_for_Fitting_a_Multidimensional_Gaussian_Function`

In [8]:

avg0[3].reshape(28,28)

array([[  3,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   2,   3,   5,   5,   6,   6,   5,   4,   2,   1,   1,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   1,   3,   7,  13,  22,  34,  46,  56,  62,  63,  60,  50,  39,  27,  16,   8,   3,   1,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   2,   6,  15,  28,  47,  71,  97, 121, 141, 155, 158, 152, 134, 107,  78,  52,  30,  13,   4,   0,   0,   0,   0],
       [  0,   0,   0,   0,   1,   6,  14,  30,  52,  81, 111, 138, 159, 175, 184, 189, 189, 179, 155, 122

In [12]:
print(avg0[0,:])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   2   2   3   4   4   3   2   2   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   1   3   6  13  24  39  52  63  66  61  49  36  21  10   4   1   0   0   0   0   0   0   0   0   0   0   0   1   4  11  24  43  69  99 126 144 150 141 119
  89  57  31  13   3   0   0   0   0   0   0   0   0   0   0   1   4  12  27  52  83 117 149 173 188 192 188 171 140 101  62  30   9   1   0   0   0   0   0   0
   0   0   1   3  10  25  52  85 122 152 173 185 189 190 192 188 170 137  94  53  20   3   0   0   0   0   0   0   0   0   1   7  21  46  80 118 150 169 173 167
 158 154 157 168 174 160 124  77  

<a id='model'></a>   

###### [Back to TOC](#toc_nb) [Previous ](#distribution) [Next ](#model)  
### Model  
 - Proof of concept for the MNIST in GMM

Parameterized model functions of the sum of single Gaussians. Use `scipy.optimize` to tweak initial guesses.

In [ ]:
import copy
import numpy as np
import matplotlib.pyplot as plt
from scipy import optimize


#data = copy.deepcopy(avg0)#"numpy array with appropriate data"
def gaussian(x, height, center, width, offset):
    return height*np.exp(-(x - center)**2/(2*width**2)) + offset

"""Need to make a function to create the Gaussians"""


"""Also need a function to create the error functions"""
errFuncs = []
for i in range(10):
    errFuncs.append(lambda p, x, y: (gaussians[i](x, *p) - y)**2)

"""guesses will be ten sets of 3 params, and 0 at the end"""
guesses = [0.49,0.55,0.01,
           0.47,0.61,0.01,
           0.39,0.58,0.01,
           0.63,0.44,0.01,
           0.55,0.47,0.01,
           0.65,0.53,0.01,
           0.57,0.56,0.01,
           0.43,0.51,0.01,
           0.45,0.49,0.01,
           0.45,0.50,0.01,
           0]
optims = []
successes = []
for i in range(10):
    optim, success = optimize.leastsq(errfunc[i], guesses[i][:], args=(data[i][:,0], data[i][:,1]))
    optims.append(optim)
    successes.append(success)




In [ ]:
plt.plot(data[0][:,0], data[0][:,1], lw=5, c='g', label='measurement')
plt.plot(data[0][:,0], gaussian(data[0][:,0], *optims[0]),
    lw=3, c='b', label='fit of N Gaussians')

plt.legend(loc='best')
#plt.savefig('result.png')

Check for the smallest residual

In [ ]:
err3 = np.sqrt(errfunc3(optim3, data[:,0], data[:,1])).sum()
err2 = np.sqrt(errfunc2(optim2, data[:,0], data[:,1])).sum()
print('Residual error when fitting 3 Gaussians: {}\n'
    'Residual error when fitting 2 Gaussians: {}'.format(err3, err2))

In [51]:
#from IPython.display import clear_output
#print("many many things")
#clear_output()

In [ ]:
#Create a new directory for your project and initialize it as a Python package.
### 4. **Create a Custom Plugin**
#Ollama plugins are created by defining custom commands that can be executed via 
#the CLI or API. Here's how to create one:

#### Step 1: Define the Command
#Create a file `command.py` in your plugin directory:


from ollama import OllamaCommand
class FilesystemCommand(OllamaCommand):
    def add_args(self, parser):
        # Add arguments for filesystem operations
        subparsers = parser.add_subparsers(title="Filesystem Operations", dest="operation")
        
        # Read file command
        read_parser = subparsers.add_parser("read-file", help="Read the contents of a file")
        read_parser.add_argument("--path", type=str, required=True, help="Path to the file")
        
        # Write file command
        write_parser = subparsers.add_parser("write-file", help="Write content to a file")
        write_parser.add_argument("--path", type=str, required=True, help="Path to the file")
        write_parser.add_argument("--content", type=str, required=True, help="Content to write")

    def handle(self, args):
        if args.operation == "read-file":
            with open(args.path, "r") as f:
                return f.read()
        elif args.operation == "write-file":
            with open(args.path, "w") as f:
                f.write(args.content)
            return f"File '{args.path}' written successfully."


#### Step 2: Register the Plugin
#Create a `setup.py` file in your plugin directory to register the command:

from setuptools import setup

setup(
    name="filesystem_plugin",
    version="0.1",
    py_modules=["command"],
    entry_points={
        "ollama.commands": [
            "filesystem_command = command:FilesystemCommand"
        ],
    },
)
#### Step 3: Install the Plugin
#Run:
#```bash
pip install -e .
#```

### 5. **Use the Custom Command**
#After installing the plugin, you can use it with Ollama:

#### Read a File:
#```bash
ollama filesystem_command read-file --path /path/to/file.txt
#```

#### Write to a File:
#```bash
ollama filesystem_command write-file --path /path/to/file.txt --content "Your content here"
#```

### 6. **Integrate with Ollama Models**
#You can now use these file operations within your workflow with Ollama models. 
#For example, you could read a file's contents and pass it to a language model for 
#processing:
#```bash
# Read the contents of a file
CONTENT=$(ollama filesystem_command read-file --path /path/to/file.txt)

# Use the content in a prompt for a language model
ollama chat --model gpt-3 --prompt "Analyze this text: $CONTENT"
#```

### 7. **Alternative Approach: Using Python Directly**
#If you prefer not to create a plugin, you can build a script that interacts with 
#both Ollama and the filesystem:
#```python
import ollama

def read_file(path):
    with open(path, "r") as f:
        return f.read()

def write_file(path, content):
    with open(path, "w") as f:
        f.write(content)
    
# Example usage
content = read_file("/path/to/file.txt")
response = ollama.chat(model="gpt-3", prompt=f"Analyze this text: {content}")
print(response)
#```

